addons:
  apt:
    packages:
    - cmake
    - cmake-data
    - pandoc
    sources:
      - george-edison55-precise-backports

install:
  - gem install mdl

before_script:
  - cmake --version
  - mdl --version
  - pandoc --version

script:
  - mkdir -pv build
  - cd build
  - cmake ..
  - cmake --build . --target all
  - ctest -VV

sudo: false
